"""add server_default=func.now() for updated_at

Revision ID: d6bb36d0a76f
Revises: 27e49862aa2e
Create Date: 2025-06-24 01:40:14.043351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6bb36d0a76f'
down_revision: Union[str, Sequence[str], None] = '27e49862aa2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
